# set PATH so it includes user's private bin if it exists
if [[ -d "$HOME/bin" ]]; then
	PATH="$HOME/bin:$PATH"
fi

# xdg-derived, systemd file-hierarchy
if [[ -d "$HOME/.local/bin" ]]; then
	PATH="$HOME/.local/bin:$PATH"
fi

if [[ -d "$HOME/.files/bin" ]]; then
	PATH="$HOME/.files/bin:$PATH"
fi

# Default editor
export EDITOR=/usr/bin/vim

# Ignore CTRL-D for five times before exiting shell
export IGNOREEOF=5

# devvm GO bin and GOPATH overrides
export PATH=/opt/golang1.12/bin:$PATH:$HOME/go/bin
if [ $HOSTNAME == "ep-vm-aws" ]
then
    export GOPATH=$HOME/go:$HOME/threepo
else
    export GOPATH=$HOME/go:/vagrant/threepo
fi


# use fd instead of find in fzf
# honors .fdignore per dir
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
